//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_ChiefCommunicationsOfficer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_ChiefCommunicationsOfficer()
        {
            this.PropertyApplicationDetails = new HashSet<PropertyApplicationDetail>();
        }
    
        public int ChiefCommunicationsOfficerCode { get; set; }
        public string ChiefCommunicationsOfficerName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyApplicationDetail> PropertyApplicationDetails { get; set; }
    }
}
