//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog_PropertyTitle
    {
        public int original_Locationid { get; set; }
        public Nullable<int> new_Locationid { get; set; }
        public string original_Volume { get; set; }
        public string new_Volume { get; set; }
        public int original_Folio { get; set; }
        public Nullable<int> new_Folio { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> AuditAction { get; set; }
        public Nullable<int> original_Project_Code { get; set; }
        public Nullable<int> new_Project_Code { get; set; }
        public string original_Project_Desc { get; set; }
        public string new_Project_Desc { get; set; }
        public Nullable<bool> original_Verified { get; set; }
        public Nullable<bool> new_Verified { get; set; }
        public string original_Title_Reference { get; set; }
        public string new_Title_Reference { get; set; }
        public Nullable<int> original_TypeCode { get; set; }
        public Nullable<int> new_TypeCode { get; set; }
        public Nullable<int> original_LandTypeCode { get; set; }
        public Nullable<int> new_LandTypeCode { get; set; }
        public string original_Unit_No { get; set; }
        public string new_Unit_No { get; set; }
        public string original_Plan_No { get; set; }
        public string new_Plan_No { get; set; }
        public string original_Block_No { get; set; }
        public string new_Block_No { get; set; }
        public string original_Flat_N0 { get; set; }
        public string new_Flat_N0 { get; set; }
        public Nullable<int> original_Regionnum { get; set; }
        public Nullable<int> new_Regionnum { get; set; }
        public Nullable<int> original_DistrictID { get; set; }
        public Nullable<int> new_DistrictID { get; set; }
        public Nullable<int> original_County_ID { get; set; }
        public Nullable<int> new_County_ID { get; set; }
        public Nullable<int> original_Subcounty_ID { get; set; }
        public Nullable<int> new_Subcounty_ID { get; set; }
        public Nullable<int> original_Parish_ID { get; set; }
        public Nullable<int> new_Parish_ID { get; set; }
        public string original_Town_Village { get; set; }
        public string new_Town_Village { get; set; }
        public string original_Street { get; set; }
        public string new_Street { get; set; }
        public string original_Plot_No { get; set; }
        public string new_Plot_No { get; set; }
        public Nullable<System.DateTime> original_Lease_Start_Date { get; set; }
        public Nullable<System.DateTime> new_Lease_Start_Date { get; set; }
        public Nullable<System.DateTime> original_Lease_End_Date { get; set; }
        public Nullable<System.DateTime> new_Lease_End_Date { get; set; }
        public Nullable<int> original_Ground_Rent { get; set; }
        public Nullable<int> new_Ground_Rent { get; set; }
        public Nullable<int> original_Rates { get; set; }
        public Nullable<int> new_Rates { get; set; }
        public string original_OfferNo { get; set; }
        public string new_OfferNo { get; set; }
        public string original_Purchaser_Name { get; set; }
        public string new_Purchaser_Name { get; set; }
        public Nullable<int> original_Nationality { get; set; }
        public Nullable<int> new_Nationality { get; set; }
        public string original_Purchasers_Address { get; set; }
        public string new_Purchasers_Address { get; set; }
        public string original_Purchasers_TelNo { get; set; }
        public string new_Purchasers_TelNo { get; set; }
        public string original_Purchasers_Email { get; set; }
        public string new_Purchasers_Email { get; set; }
        public string original_PurchaserEmployer { get; set; }
        public string new_PurchaserEmployer { get; set; }
        public string original_Offer_Value { get; set; }
        public string new_Offer_Value { get; set; }
        public Nullable<System.DateTime> original_OfferDate { get; set; }
        public Nullable<System.DateTime> new_OfferDate { get; set; }
        public Nullable<System.DateTime> original_OfferExpiryDate { get; set; }
        public Nullable<System.DateTime> new_OfferExpiryDate { get; set; }
        public Nullable<System.DateTime> original_OfferPaymentDate { get; set; }
        public Nullable<System.DateTime> new_OfferPaymentDate { get; set; }
        public Nullable<bool> original_OfferPaidUP { get; set; }
        public Nullable<System.DateTime> new_OfferPaidUP { get; set; }
        public string original_LeaseOfferedBy { get; set; }
        public string new_LeaseOfferedBy { get; set; }
        public Nullable<bool> original_TitleTransferred { get; set; }
        public Nullable<bool> new_TitleTransferred { get; set; }
        public Nullable<System.DateTime> original_TransferDate { get; set; }
        public Nullable<System.DateTime> new_TransferDate { get; set; }
        public string original_PurchaserRemark { get; set; }
        public string new_PurchaserRemark { get; set; }
        public string original_NewDataAudit { get; set; }
        public string new_NewDataAudit { get; set; }
        public string original_EditDataAudit { get; set; }
        public string new_EditDataAudit { get; set; }
        public string original_PropertyStaatus { get; set; }
        public string new_PropertyStaatus { get; set; }
        public string original_AreaOfUnit { get; set; }
        public string new_AreaOfUnit { get; set; }
        public string original_FloorAreaLeased { get; set; }
        public string new_FloorAreaLeased { get; set; }
        public string original_UnitFactor { get; set; }
        public string new_UnitFactor { get; set; }
        public Nullable<System.DateTime> original_Date { get; set; }
        public Nullable<System.DateTime> new_Date { get; set; }
        public Nullable<System.DateTime> original_RegDate { get; set; }
        public Nullable<System.DateTime> new_RegDate { get; set; }
        public string original_InstrumentNo { get; set; }
        public string new_InstrumentNo { get; set; }
        public string original_ProprietorName { get; set; }
        public string new_ProprietorName { get; set; }
        public string original_ProprietorAddress { get; set; }
        public string new_ProprietorAddress { get; set; }
        public string original_FathersName { get; set; }
        public string new_FathersName { get; set; }
        public string original_Clan { get; set; }
        public string new_Clan { get; set; }
        public string original_Registrar { get; set; }
        public string new_Registrar { get; set; }
        public string original_BoardMinuteRelease { get; set; }
        public string new_BoardMinuteRelease { get; set; }
        public string original_Directors { get; set; }
        public string new_Directors { get; set; }
        public string original_Added_By { get; set; }
        public string new_Added_By { get; set; }
        public Nullable<System.DateTime> original_Added_Date { get; set; }
        public Nullable<System.DateTime> new_Added_Date { get; set; }
        public string original_Edited_By { get; set; }
        public string new_Edited_By { get; set; }
        public Nullable<System.DateTime> original_Edited_Date { get; set; }
        public Nullable<System.DateTime> new_Edited_Date { get; set; }
        public Nullable<System.DateTime> original_Deleted_Date { get; set; }
        public Nullable<System.DateTime> new_Deleted_Date { get; set; }
        public string original_Deleted_By { get; set; }
        public string new_Deleted_By { get; set; }
        public string original_Unlocked_By { get; set; }
        public string new_Unlocked_By { get; set; }
        public Nullable<System.DateTime> original_Unlocked_Date { get; set; }
        public Nullable<System.DateTime> new_Unlocked_Date { get; set; }
        public Nullable<int> original_PlotSize_ID { get; set; }
        public Nullable<int> new_PlotSize_ID { get; set; }
        public string original_valueOfProperty { get; set; }
        public string new_valueOfProperty { get; set; }
        public Nullable<int> original_LeaseYears_ID { get; set; }
        public Nullable<int> new_LeaseYears_ID { get; set; }
        public string original_ActualPlotSize { get; set; }
        public string new_ActualPlotSize { get; set; }
        public string original_SourceOfLease { get; set; }
        public string new_SourceOfLease { get; set; }
        public string original_GroundRentNarrative { get; set; }
        public string new_GroundRentNarrative { get; set; }
        public Nullable<System.DateTime> original_GroundRentDueDate { get; set; }
        public Nullable<System.DateTime> new_GroundRentDueDate { get; set; }
        public string original_GeneralRemarks { get; set; }
        public string new_GeneralRemarks { get; set; }
        public string original_Valuer { get; set; }
        public string new_Valuer { get; set; }
        public Nullable<System.DateTime> original_DateOfValuation { get; set; }
        public Nullable<System.DateTime> new_DateOfValuation { get; set; }
        public Nullable<bool> original_PropertySoldorTransferred { get; set; }
        public Nullable<bool> new_PropertySoldorTransferred { get; set; }
        public Nullable<int> original_Project_CodeParent { get; set; }
        public Nullable<int> new_Project_CodeParent { get; set; }
        public string original_VolumeParent { get; set; }
        public string new_VolumeParent { get; set; }
        public Nullable<int> original_FolioParent { get; set; }
        public Nullable<int> new_FolioParent { get; set; }
        public Nullable<bool> original_UnlockTitle { get; set; }
        public Nullable<bool> new_UnlockTitle { get; set; }
        public Nullable<int> original_TitleMovementStatusID { get; set; }
        public Nullable<int> new_TitleMovementStatusID { get; set; }
        public Nullable<bool> original_TitleSentBackToEntrant { get; set; }
        public Nullable<bool> new_TitleSentBackToEntrant { get; set; }
        public Nullable<bool> original_FinalSubmission { get; set; }
        public Nullable<bool> new_FinalSubmission { get; set; }
        public string original_RejectionComment { get; set; }
        public string new_RejectionComment { get; set; }
        public string original_UnlockComment { get; set; }
        public string new_UnlockComment { get; set; }
        public string original_UnlockedBy { get; set; }
        public string new_UnlockedBy { get; set; }
        public Nullable<System.DateTime> original_UnlockDate { get; set; }
        public Nullable<System.DateTime> new_UnlockDate { get; set; }
        public Nullable<double> Original_Latitude { get; set; }
        public Nullable<double> New_Latitude { get; set; }
        public Nullable<double> Original_Longitude { get; set; }
        public Nullable<double> New_Longitude { get; set; }
    
        public virtual District District { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual PropertyTitle PropertyTitle { get; set; }
        public virtual PropertyTitle PropertyTitle1 { get; set; }
    }
}
