//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DestinationType()
        {
            this.AuditLog_PropertyTitleMovt = new HashSet<AuditLog_PropertyTitleMovt>();
            this.AuditLog_PropertyTitleMovt1 = new HashSet<AuditLog_PropertyTitleMovt>();
            this.PropertyTitleMovts = new HashSet<PropertyTitleMovt>();
        }
    
        public int DestinyCode { get; set; }
        public string DestinyDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLog_PropertyTitleMovt> AuditLog_PropertyTitleMovt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLog_PropertyTitleMovt> AuditLog_PropertyTitleMovt1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyTitleMovt> PropertyTitleMovts { get; set; }
    }
}
