//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpiryNotification
    {
        public int NotificationID { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public Nullable<int> ReminderNo { get; set; }
        public Nullable<int> ReminderStatus { get; set; }
        public string Email { get; set; }
        public string MobiTel { get; set; }
        public string Title_Reference { get; set; }
        public string ReminderDetails { get; set; }
    }
}
