//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationServer
    {
        public int HostID { get; set; }
        public string SenderEmail { get; set; }
        public string SenderPassword { get; set; }
        public string SMTP_Port { get; set; }
        public string SMTP_Host { get; set; }
        public Nullable<bool> EnableSSL { get; set; }
        public Nullable<bool> Default_Host { get; set; }
        public Nullable<int> No_Reminders { get; set; }
        public Nullable<short> Reminder_Interval { get; set; }
        public string Remindees { get; set; }
    
        public virtual NotificationReminderInterval NotificationReminderInterval { get; set; }
    }
}
