//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int Location_id { get; set; }
        public int OfferNo { get; set; }
        public string Volume { get; set; }
        public int Folio { get; set; }
        public Nullable<int> Project_code { get; set; }
        public Nullable<int> Project_id { get; set; }
        public string Title_Reference { get; set; }
        public string Purchaser_Name { get; set; }
        public string Nationality { get; set; }
        public string Purchasers_Address { get; set; }
        public string Purchasers_TelNo { get; set; }
        public string Purchasers_Email { get; set; }
        public string PurchaserEmployer { get; set; }
        public Nullable<int> Offer_Value { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public Nullable<System.DateTime> OfferExpiryDate { get; set; }
        public Nullable<System.DateTime> OfferPaymentDate { get; set; }
        public Nullable<bool> OfferPaidUP { get; set; }
        public Nullable<bool> TitleTransferred { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string PurchaserRemark { get; set; }
        public string NewDataAudit { get; set; }
        public string EditDataAudit { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<int> SealApplicationRegister { get; set; }
    }
}
