//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parish
    {
        public int Parish_ID { get; set; }
        public Nullable<int> Subcounty_ID { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> County { get; set; }
        public string Parish_Name { get; set; }
    
        public virtual County County1 { get; set; }
        public virtual District District1 { get; set; }
        public virtual Subcounty Subcounty { get; set; }
    }
}
