//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyApplication
    {
        public string Client_ID { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<bool> ClientWithdrawn { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public Nullable<bool> IsRecordValid { get; set; }
        public string Notes { get; set; }
    
        public virtual PropertyApplicant PropertyApplicant { get; set; }
        public virtual PropertyApplicationDetail PropertyApplicationDetail { get; set; }
        public virtual User_NHCC User_NHCC { get; set; }
        public virtual User_NHCC User_NHCC1 { get; set; }
    }
}
