//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Payment
    {
        public int Location_id { get; set; }
        public int OfferNo { get; set; }
        public string Volume { get; set; }
        public int Folio { get; set; }
        public string Payment_Ref_No { get; set; }
        public Nullable<int> Project_Code { get; set; }
        public string Project_Desc { get; set; }
        public string Title_Reference { get; set; }
        public Nullable<System.DateTime> Pay_Date { get; set; }
        public Nullable<int> PayMethodCode { get; set; }
        public Nullable<int> AmountPaid { get; set; }
        public string Payment_Details { get; set; }
        public string NewDataAudit { get; set; }
        public string EditDataAudit { get; set; }
        public string Added_By { get; set; }
        public Nullable<System.DateTime> Added_Date { get; set; }
        public string Edited_By { get; set; }
        public Nullable<System.DateTime> Edited_Date { get; set; }
        public string GrroundRent { get; set; }
        public string PropertyRates { get; set; }
        public string Amount_in_Words { get; set; }
        public Nullable<bool> UnlockTitle { get; set; }
        public Nullable<int> PropertyPaymentStatusID { get; set; }
        public Nullable<bool> PropertyPaymentSentBackToEntrant { get; set; }
        public Nullable<bool> FinalSubmission { get; set; }
        public string RejectionComment { get; set; }
        public string GeneralRemarks { get; set; }
        public string UnlockComment { get; set; }
        public string UnlockedBy { get; set; }
        public Nullable<System.DateTime> UnlockDate { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
    
        public virtual AuditLog_PropertyPayment AuditLog_PropertyPayment { get; set; }
        public virtual PayMethod PayMethod { get; set; }
        public virtual Property_Payment Property_Payment1 { get; set; }
        public virtual Property_Payment Property_Payment2 { get; set; }
    }
}
