//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_OffersManagement
    {
        public string Project_Desc { get; set; }
        public string StatusDesc { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
    }
}
