//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_AuditLog_PropertyTitleMovt
    {
        public Nullable<int> original_Project_Code { get; set; }
        public string OriginalProjectDesc { get; set; }
        public Nullable<int> new_Project_Code { get; set; }
        public string NewProjectDesc { get; set; }
        public Nullable<int> original_Lawyers_ID { get; set; }
        public string OriginalLawyersDesc { get; set; }
        public Nullable<int> new_Lawyers_ID { get; set; }
        public string NewLawyersDesc { get; set; }
        public Nullable<int> original_TitleMovementStatusID { get; set; }
        public string OriginalTitleMovtStatusDesc { get; set; }
        public Nullable<int> new_TitleMovementStatusID { get; set; }
        public string NewTitleMovtStatusDesc { get; set; }
        public Nullable<int> AuditAction { get; set; }
        public Nullable<int> original_Dest_Category { get; set; }
        public string OriginalDestinationCatDesc { get; set; }
        public Nullable<int> new_Dest_Category { get; set; }
        public string NewDestinationCatDesc { get; set; }
        public Nullable<bool> original_Ooutward { get; set; }
        public string OriginalOutward { get; set; }
        public Nullable<bool> new_Ooutward { get; set; }
        public string NewOutward { get; set; }
        public Nullable<int> original_Purpose_ID { get; set; }
        public string OriginalPurposeDesc { get; set; }
        public Nullable<int> new_Purpose_ID { get; set; }
        public string NewPurposeDesc { get; set; }
        public int original_Movt_Serial_No { get; set; }
        public Nullable<int> new_Movt_Serial_No { get; set; }
        public int original_Folio { get; set; }
        public Nullable<int> new_Folio { get; set; }
        public string original_Volume { get; set; }
        public string new_Volume { get; set; }
        public string original_Title_Reference { get; set; }
        public string new_Title_Reference { get; set; }
        public Nullable<System.DateTime> original_Movement_Date { get; set; }
        public Nullable<System.DateTime> new_Movement_Date { get; set; }
        public Nullable<System.DateTime> original_Return_Date { get; set; }
        public Nullable<System.DateTime> new_Return_Date { get; set; }
        public Nullable<bool> original_TransferInNHCC { get; set; }
        public Nullable<bool> new_TransferInNHCC { get; set; }
        public string original_DestinationDesc { get; set; }
        public string new_DestinationDesc { get; set; }
        public string original_Destination_Address { get; set; }
        public string new_Destination_Address { get; set; }
        public string original_Email { get; set; }
        public string new_Email { get; set; }
        public string new_TelNo { get; set; }
        public string original_TelNo { get; set; }
        public string original_Directors { get; set; }
        public string new_Directors { get; set; }
        public string original_WebSite { get; set; }
        public string new_WebSite { get; set; }
        public string original_Remark { get; set; }
        public string new_Remark { get; set; }
        public string original_NewDataAudit { get; set; }
        public string new_NewDataAudit { get; set; }
        public string original_EditDataAudit { get; set; }
        public string new_EditDataAudit { get; set; }
        public string original_FlatNo { get; set; }
        public string new_FlatNo { get; set; }
        public string original_UnitNo { get; set; }
        public string new_UnitNo { get; set; }
        public Nullable<bool> original_HasVolumeFolio { get; set; }
        public Nullable<bool> new_HasVolumeFolio { get; set; }
        public Nullable<System.DateTime> original_Added_Date { get; set; }
        public Nullable<System.DateTime> new_Added_Date { get; set; }
        public Nullable<System.DateTime> original_Edited_Date { get; set; }
        public Nullable<System.DateTime> new_Edited_Date { get; set; }
        public string original_Deleted_By { get; set; }
        public string new_Deleted_By { get; set; }
        public Nullable<System.DateTime> original_Deleted_Date { get; set; }
        public Nullable<System.DateTime> new_Deleted_Date { get; set; }
        public Nullable<System.DateTime> original_Unlocked_Date { get; set; }
        public Nullable<System.DateTime> new_Unlocked_Date { get; set; }
        public string original_PlotNo { get; set; }
        public string new_PlotNo { get; set; }
        public string original_LawyersNames { get; set; }
        public string new_LawyersNames { get; set; }
        public Nullable<bool> original_Additional { get; set; }
        public Nullable<bool> new_Additional { get; set; }
        public string original_Additional_Information { get; set; }
        public string new_Additional_Information { get; set; }
        public Nullable<bool> original_UnlockTitle { get; set; }
        public Nullable<bool> new_UnlockTitle { get; set; }
        public Nullable<bool> original_TitleSentBackToEntrant { get; set; }
        public Nullable<bool> new_TitleSentBackToEntrant { get; set; }
        public Nullable<bool> original_FinalSubmission { get; set; }
        public Nullable<bool> new_FinalSubmission { get; set; }
        public string original_RejectionComment { get; set; }
        public string new_RejectionComment { get; set; }
        public string original_UnlockComment { get; set; }
        public Nullable<bool> original_MovementStatus { get; set; }
        public string new_UnlockComment { get; set; }
        public Nullable<bool> new_MovementStatus { get; set; }
        public string original_UnlockedBy { get; set; }
        public string new_UnlockedBy { get; set; }
        public Nullable<System.DateTime> original_UnlockDate { get; set; }
        public Nullable<System.DateTime> new_UnlockDate { get; set; }
        public string AuditAction_Description { get; set; }
        public string original_Added_By { get; set; }
        public string OriginalAddedByDesc { get; set; }
        public string new_Added_By { get; set; }
        public string NewAddedByDesc { get; set; }
        public string original_Edited_By { get; set; }
        public string OriginalEditedByDesc { get; set; }
        public string new_Edited_By { get; set; }
        public string NewEditedByDesc { get; set; }
        public string original_Unlocked_By { get; set; }
        public string new_Unlocked_By { get; set; }
        public int original_Locationid { get; set; }
        public string OriginalLocationDesc { get; set; }
        public Nullable<int> new_Locationid { get; set; }
        public string NewLocationDesc { get; set; }
        public string OriginalUnlockedByDesc { get; set; }
        public string NewUnlockedByDesc { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> OriginalLandTypeCode { get; set; }
        public string OriginalLandTypeDesc { get; set; }
        public Nullable<int> NewLandTypeCode { get; set; }
        public string NewLandTypeDesc { get; set; }
        public Nullable<int> OriginalTypeCode { get; set; }
        public string OriginalTypeCodeDesc { get; set; }
        public Nullable<int> NewTypeCode { get; set; }
        public string NewTypeCodeDesc { get; set; }
    }
}
