//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_PropertyPament
    {
        public int Location_id { get; set; }
        public string LocationDescription { get; set; }
        public Nullable<int> Project_Code { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<int> PayMethodCode { get; set; }
        public string PayMethodDescription { get; set; }
        public string Title_Reference { get; set; }
        public string TitleReferencePropTitle { get; set; }
        public Nullable<int> LandTypeCodePropTitle { get; set; }
        public string LandTypeCodeDescPropTitle { get; set; }
        public Nullable<int> TypeCodePropTitle { get; set; }
        public string TypeCodeDescPropTitle { get; set; }
        public int OfferNo { get; set; }
        public string Volume { get; set; }
        public int Folio { get; set; }
        public string Payment_Ref_No { get; set; }
        public string Project_Desc { get; set; }
        public Nullable<System.DateTime> Pay_Date { get; set; }
        public Nullable<int> AmountPaid { get; set; }
        public string Payment_Details { get; set; }
        public string NewDataAudit { get; set; }
        public string EditDataAudit { get; set; }
        public string Added_By { get; set; }
        public Nullable<System.DateTime> Added_Date { get; set; }
        public string Edited_By { get; set; }
        public Nullable<System.DateTime> Edited_Date { get; set; }
        public string GrroundRent { get; set; }
        public string PropertyRates { get; set; }
        public string Amount_in_Words { get; set; }
        public Nullable<bool> UnlockTitle { get; set; }
        public Nullable<int> PropertyPaymentStatusID { get; set; }
        public Nullable<bool> PropertyPaymentSentBackToEntrant { get; set; }
        public Nullable<bool> FinalSubmission { get; set; }
        public string RejectionComment { get; set; }
        public string GeneralRemarks { get; set; }
        public string UnlockComment { get; set; }
        public string UnlockedBy { get; set; }
        public Nullable<System.DateTime> UnlockDate { get; set; }
    }
}
