//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Menu_Option
    {
        public string UserName { get; set; }
        public string MenuItem_Type { get; set; }
        public string MenuItem_Key { get; set; }
        public Nullable<bool> MenuItem_Enabled { get; set; }
        public Nullable<bool> MenuItem_Visible { get; set; }
    
        public virtual User_NHCC User_NHCC { get; set; }
    }
}
