//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_A_SubcountyList
    {
        public int County_ID { get; set; }
        public int District_ID { get; set; }
        public string County_Name { get; set; }
        public int Subcounty_ID { get; set; }
        public Nullable<int> District { get; set; }
        public string Subcounty_Name { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
