//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAudPropPaymentAspNetUsersFullName
    {
        public string original_Added_By { get; set; }
        public string OrigAddedByFullnames { get; set; }
        public string new_Added_By { get; set; }
        public string NewAddedByFullnames { get; set; }
        public string original_Edited_By { get; set; }
        public string OrigEditedByFullnames { get; set; }
        public string new_Edited_By { get; set; }
        public string NewEditedByFullnames { get; set; }
        public string original_UnlockedBy { get; set; }
        public string OrigUnlockedByFullnames { get; set; }
        public string new_UnlockedBy { get; set; }
        public string NewUnlockedByFullnames { get; set; }
        public int original_Locationid { get; set; }
        public Nullable<int> new_Locationid { get; set; }
        public int original_OfferNo { get; set; }
        public Nullable<int> new_OfferNo { get; set; }
        public string original_Volume { get; set; }
        public string new_Volume { get; set; }
        public int original_Folio { get; set; }
        public Nullable<int> new_Folio { get; set; }
        public string original_Payment_Ref_No { get; set; }
        public string new_Payment_Ref_No { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> original_Project_Code { get; set; }
        public Nullable<int> new_Project_Code { get; set; }
        public string original_Title_Reference { get; set; }
        public string new_Title_Reference { get; set; }
        public Nullable<System.DateTime> original_Pay_Date { get; set; }
        public Nullable<System.DateTime> new_Pay_Date { get; set; }
        public Nullable<int> original_PayMethodCode { get; set; }
        public Nullable<int> new_PayMethodCode { get; set; }
        public Nullable<int> original_AmountPaid { get; set; }
        public Nullable<int> new_AmountPaid { get; set; }
        public string original_Payment_Details { get; set; }
        public string new_Payment_Details { get; set; }
        public string original_NewDataAudit { get; set; }
        public string new_NewDataAudit { get; set; }
        public string original_EditDataAudit { get; set; }
        public string new_EditDataAudit { get; set; }
        public Nullable<System.DateTime> original_Added_Date { get; set; }
        public Nullable<System.DateTime> new_Added_Date { get; set; }
        public Nullable<System.DateTime> original_Edited_Date { get; set; }
        public Nullable<System.DateTime> new_Edited_Date { get; set; }
        public string original_GrroundRent { get; set; }
        public string new_GrroundRent { get; set; }
        public string original_PropertyRates { get; set; }
        public string new_PropertyRates { get; set; }
        public string original_Amount_in_Words { get; set; }
        public string new_Amount_in_Words { get; set; }
        public Nullable<bool> original_UnlockTitle { get; set; }
        public Nullable<bool> new_UnlockTitle { get; set; }
        public Nullable<int> original_PropertyPaymentStatusID { get; set; }
        public Nullable<int> new_PropertyPaymentStatusID { get; set; }
        public Nullable<bool> new_PropertyPaymentSentBackToEntrant { get; set; }
        public Nullable<bool> original_PropertyPaymentSentBackToEntrant { get; set; }
        public Nullable<bool> original_FinalSubmission { get; set; }
        public Nullable<bool> new_FinalSubmission { get; set; }
        public string original_RejectionComment { get; set; }
        public string new_RejectionComment { get; set; }
        public string original_GeneralRemarks { get; set; }
        public string new_GeneralRemarks { get; set; }
        public string original_UnlockComment { get; set; }
        public string new_UnlockComment { get; set; }
        public Nullable<System.DateTime> original_UnlockDate { get; set; }
        public Nullable<System.DateTime> new_UnlockDate { get; set; }
        public Nullable<int> AuditAction { get; set; }
    }
}
