//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_LeasePeriodNotification
    {
        public int Location_id { get; set; }
        public string Volume { get; set; }
        public int Folio { get; set; }
        public Nullable<int> Project_Code { get; set; }
        public Nullable<int> Project_id { get; set; }
        public Nullable<bool> Verified { get; set; }
        public string Title_Reference { get; set; }
        public Nullable<int> LandTypeCode { get; set; }
        public Nullable<System.DateTime> Lease_Start_Date { get; set; }
        public Nullable<System.DateTime> Lease_End_Date { get; set; }
        public Nullable<int> RemainingYears { get; set; }
        public Nullable<int> RemainingMonths { get; set; }
        public Nullable<int> RemainingDays { get; set; }
        public string Project_Desc { get; set; }
        public string Location_Desc { get; set; }
    }
}
