//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_A_DocumentUpload
    {
        public string DocumentCode { get; set; }
        public string TitleReferenceNo { get; set; }
        public string Volume { get; set; }
        public Nullable<int> Folio { get; set; }
        public string FileURL { get; set; }
        public string FileType { get; set; }
        public string DocumentName { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string DeletedBy { get; set; }
    }
}
