//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewNewRegionDistrict
    {
        public int DistrictID { get; set; }
        public string District_Name { get; set; }
        public int Region_code { get; set; }
        public string NewDataAudit { get; set; }
        public string EditDataAudit { get; set; }
        public string Added_By { get; set; }
        public Nullable<System.DateTime> Added_Date { get; set; }
        public string Edited_By { get; set; }
        public Nullable<System.DateTime> Edited_Date { get; set; }
        public Nullable<int> Region_num { get; set; }
        public string Region_name { get; set; }
    }
}
