pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["activity_capturing_deadline.htm","Calender of Activities &#62; Activity Capturing Deadline","Calender of Activities Activity Capturing Deadline Navigation: Calender of Activities Activity Capturing Deadline This form is used by the adminis...",""],
["appointment_window.htm","Calender of Activities &#62; Working with Activities (Appointments) &#62; Add/Edit Activity (Appointment) Window","Calender of Activities Working with Activities (Appointments) Add/Edit Activity (Appointment) Window Navigation: Calender of Activities Working wi...",""],
["calender_of_activites.htm","Calender of Activities","Scheduler is an event calendar that manages the list of various activities (events/appointments) in different available views (day, week, workweek...",""],
["chapter_2.htm","Decisions/Directives","Decisions / Directives Navigation: No topics above this level Decisions / Directives The decision and Directive monitors decisions made by the Cou...",""],
["common_market_protocol.htm","Common Market Protocol","Common Market Protocol Navigation: No topics above this level Common Market Protocol This allows for the monitoring of all protocols of the Common...",""],
["common_market_utilities.htm","Common Market Protocol &#62; Common Market Utilities","Common Market Protocol Common Market Utilities Navigation: Common Market Protocol Common Market Utilities The process of managing the Common Marke...",""],
["compedium_report.htm","Decisions/Directives &#62; Compedium Report","Decisions/Directives Compedium Report Navigation: Decisions/Directives Compedium Report The Decision Compendium Report predicate is used to view t...",""],
["conflicting_policy_meetings.htm","Calender of Activities &#62; Conflicting Policy Meetings","Calender of Activities Conflicting Policy Meetings Navigation: Calender of Activities Conflicting Policy Meetings This form shows the list of conf...",""],
["dialog_template.htm","Introduction &#62; Common Features &#62; Dialog Template","Introduction Common Features Dialog Template Navigation: Introduction Common Features Dialog Template Overview This displays Dialog window within ...",""],
["eams_manual_ftsearch.htm"," ","Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this version of the search eng...",""],
["edit_activities.htm","Calender of Activities &#62; Edit Activities","Calender of Activities We have a search grid parametrized with: Organ / Institution, Planning Period (Months), Directorate, Planning Period (Year)...",""],
["edit_decision___directive.htm","Decisions/Directives &#62; Edit Decision / Directive","Decisions/Directives Edit Decision / Directive Navigation: Decisions/Directives Edit Decision / Directive The Administrators of the system have th...",""],
["file_uploads.htm","Non- Tarrif Barriers (NTBs) &#62; Registering and Tracking Complaints &#62; File uploads","Non- Tarrif Barriers (NTBs) Registering and Tracking Complaints File Uploads (Supporting Documents) Navigation: Non- Tarrif Barriers (NTBs) Regist...",""],
["forward_activities.htm","Calender of Activities &#62; Forward Activities","Calender of Activities Forward Activities Navigation: Calender of Activities Forward Activities To Forward an activity, click on the form below an...",""],
["introduction.htm","Introduction","Introduction Navigation: No topics above this level Introduction The EAC Monitoring and Evaluation System (EAMS) is computerized system used to pr...",""],
["non-_tarrif_barriers_ntbs.htm","Non- Tarrif Barriers (NTBs)","Non- Tarrif Barriers (NTBs) Navigation: No topics above this level Non- Tarrif Barriers (NTBs) The web-based NTBs mechanism will enhance transpare...",""],
["ntb_foca_lperson.htm","Non- Tarrif Barriers (NTBs) &#62; NTB Foca lPerson","Non- Tarrif Barriers (NTBs) NTB Foca lPerson Navigation: Non- Tarrif Barriers (NTBs) NTB Foca lPerson To add a new focal point person for NTB, fol...",""],
["overview.htm","Decisions/Directives &#62; Add new Decision / Directive","Decisions/Directives Add/Edit Decision / Directive Navigation: Decisions/Directives Add/Edit Decision / Directive Manage Static Information The pr...",""],
["registering_and_tracking_compl.htm","Non- Tarrif Barriers (NTBs) &#62; Registering and Tracking Complaints","Non- Tarrif Barriers (NTBs) Registering and Tracking Complaints Navigation: Non- Tarrif Barriers (NTBs) Registering and Tracking Complaints All re...",""],
["report.htm","Calender of Activities &#62; Report","Calender of Activities Report Navigation: Calender of Activities Report The Reports essentially provides the user with the capability to view, exp...",""],
["rotational_activities_by_partn.htm","Calender of Activities &#62; Rotational Activities by Partner States","Calender of Activities Rotational Activities by Partner States Navigation: Calender of Activities Rotational Activities by Partner States This for...",""],
["second_topic.htm","Introduction &#62; Common Features","Introduction Common Features Navigation: Introduction Common Features There are common features that are characteristically present in the main su...",""],
["summary_trends.htm","Common Market Protocol &#62; Summary Trends","Common Market Protocol Summary Trends Navigation: Common Market Protocol Summary Trends This module shows the summary of trend for a particular in...",""],
["track_a_complaint.htm","Non- Tarrif Barriers (NTBs) &#62; Track a Complaint","Non- Tarrif Barriers (NTBs) Track a Complaint Navigation: Non- Tarrif Barriers (NTBs) Track a Complaint Users can track the status of complaints w...",""],
["update_history.htm","Decisions/Directives &#62; Update History","Decisions/Directives Update History Navigation: Decisions/Directives Update History The Update History module is used to track changes made in the...",""],
["update_progressive_information.htm","Decisions/Directives &#62; Update Progressive Information","Decisions/Directives Update Progressive Information Navigation: Decisions/Directives Update Progressive Information Update Progressive Information...",""],
["update_status_history.htm","Common Market Protocol &#62; Update Status History","Common Market Protocol Update Status History Navigation: Common Market Protocol Update Status History The Update History module is used to track c...",""],
["upload_new_decisions.htm","Decisions/Directives &#62; Upload New Decisions","Decisions/Directives Upload New Decisions Navigation: Decisions/Directives Upload New Decisions Uploading a new decision requires one to browse th...",""],
["welcome_topic.htm","Introduction &#62; System Dashboards","Introduction Using the Login Page Navigation: Introduction Using the Login Page The Login Page provides and enforces security access to the applic...",""],
["working_with_activities_appoin.htm","Calender of Activities &#62; Working with Activities (Appointments)","Calender of Activities Working with Activities (Appointments) Navigation: Calender of Activities Working with Activities (Appointments) Appointmen...",""]];
